name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: remote add
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GIT_USER_EMAIL: kei.kyoto.be.amb@gmail.com
          GIT_USER_NAME: olachinkei
        run: |
          echo "Cloning destination git repository"
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"
          CLONE_DIR=$(mktemp -d)
          git clone https://olachinkei:$HF_TOKEN@huggingface.co/spaces/olachinkei/covid-doc-search "$CLONE_DIR"
          ls -la "$CLONE_DIR"
          echo "Copy contents to clone git repository"
          cp -rf * "$CLONE_DIR"
          COMMIT_MESSAGE=$(git log --oneline --format=%B -n 1 HEAD | head -n 1)
          COMM=${COMM:=Sync with Github}
          echo "commit message:"
          echo "$COMMIT_MESSAGE"
          cd "$CLONE_DIR"
          echo "Files that will be pushed:"
          ls -la
          echo "git add:"
          git add -A
          echo "git status:"
          git status
          echo "git diff-index:"
          git diff-index --quiet HEAD || git commit --message "$COMMIT_MESSAGE"
          echo "git push origin:"
          git push https://olachinkei:$HF_TOKEN@huggingface.co/spaces/olachinkei/covid-doc-search main

